services:
  postgres:
    image: postgres:14
    container_name: store_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
