version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: store_postgres
    restart: unless-stopped
    ports:
    - "5433:5432"

    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
      POSTGRES_DB: store_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
